### ISSUE TITLE
My ads tab disappear

### ISSUE THREAD

**Issue by PerJensen** [RiverVanRain/market#31]
When you go to all ads and click my ads, the tab disappear.

**Comment by rohit1290** [comment]
When you are on the home page of market plugin you can see the following tab:

- All ads - All ads of the **community**
- Buying - All Buying type ads of the **community**
- Selling - All Selling type ads of the **community**
- Swap - All Swap type ads of the **community**
- Free - All Free type ads of the **community**
- My Ads - Link that takes you to user's market page

When you click on "My ads" you can see the following tab:

- All ads - All ads for which **you are the owner**
- Buying - All Buying type ads for which **you are the owner**
- Selling - All Selling type ads for which **you are the owner**
- Swap - All Swap type ads for which **you are the owner**
- Free - All Free type ads for which **you are the owner**

The tab is disappearing because there is no need of "My Ads" tabs. All the tabs that are shown after clicking "My Ads" are sub pages of "My Ads".

**Comment by RiverVanRain** [comment]
Fixed by [commit](https://github.com/RiverVanRain/market/commit/8a5df7253bcc7350362bf2f04dc3a9fe0ec940b3)
